services:
  app:
    image: ghcr.io/mahdikiani/ramayt:main
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      KAVENEGAR_API_KEY: ${KAVENEGAR_API_KEY}
      ZARINPAL_MERCHANT_ID: ${ZARINPAL_MERCHANT_ID}
      CALLBACK_URL: ${CALLBACK_URL}
      DB_PATH: /data/charity.db
    volumes:
      - ./db_data:/data
      - ./uploads_data:/app/public/uploads
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/api/campaigns"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=3001"
      # - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.scheme=https"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true
